services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-cxc
    ports:
      - "${DB_PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "${MSSQL_PID}"
      SA_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped

  ef-migrator:
    build:
      context: .
      dockerfile: CiCd/db/Dockerfile.migrator
    depends_on:
      - sqlserver
    environment:
      DB_SERVER: sqlserver
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
