services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-cxc
    ports:
      - "${DB_PORT}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "${MSSQL_PID}"
      SA_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped

  ef-migrator:
    build:
      context: .
      dockerfile: CiCd/db/Dockerfile.migrator
    depends_on:
      - sqlserver
    environment:
      DB_SERVER: sqlserver
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    
  cxc-app:
    build:
      context: .
      dockerfile: CiCd/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:80"
      DB_SERVER: sqlserver
      DB_PORT: 1433
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      BASE_CONTABILIDAD_URL: ${BASE_CONTABILIDAD_URL}
      CONTABILIDAD_API_USER: ${CONTABILIDAD_API_USER}
      CONTABILIDAD_API_PASSWORD: ${CONTABILIDAD_API_PASSWORD}
